# Generated by Django 4.2.4 on 2023-08-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jayapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abijith',
            old_name='name',
            new_name='username',
        ),
    ]
