# Generated by Django 4.2.4 on 2023-10-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jayapp', '0002_rename_name_abijith_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='saaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'saaa',
            },
        ),
    ]
